name: opticash
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons:
  dio:
  pretty_dio_logger:
  flutter_svg:
  jiffy:
  stacked:
  get_it:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Rogerex
      fonts:
        - asset: assets/fonts/RogerexRegular.ttf          
        - asset: assets/fonts/RogerexMedium.ttf
          weight: 400
        - asset: assets/fonts/RogerexSemiBold.ttf
          weight: 500
        - asset: assets/fonts/RogerexBold.ttf
          weight: 600
        - asset: assets/fonts/RogerexExtraBold.ttf
          weight: 700
        - asset: assets/fonts/RogerexBlack.ttf
          weight: 800
        - asset: assets/fonts/RogerexMax.ttf
          weight: 900

